language: ruby
rvm:
- 2.3.3
deploy:
  provider: heroku
  api_key:
    secure: YTvMdb6X6GdDoe0egxDY0a0MRwpahdrn/+Wxfz/UmbaMwYDlPu/ChKUaF8chvvZTPwQBVBLR7RgkBPh+BCYG9m3skJJ9Oyu9mjwS65hU1hbgXxkQ+yx1TD3LuxcTnxYazD+q7p9su0z2vq2j7xuwo+eUZR3PCIGMP0rKWDC4VrN4eVBeMcpgvvVaSIA3N2ptXYkYecaL312N+MqFvs99MhUH0lUoJFjTBfJLWuTzr6SrqHdjDA1Qb5GFpLYADSWruj5wLaK2BDzOmwrrpEAx4MsFT5NG545T8372W6kqgBpAMTVJW02chtHXOHBOdXsrObgLbHLX25zvbkM7JWfXxGCRAzG7mwo2w76DFooypxA3j4IszqCpuodvsSm9REgcTVJQkQcfvwmvJGtQfEYhJ7qybVgxWwGH54ZFJwi5BJ7EqUlLfCkjyNXAqJaTJ+A8RjitvJDcghtYouZSQYjLq+8oPYpOqr7u/sGNzA2OONFXftZqbxfhlbKcZWq9Ij6Kx71E9ZVhdccth1nrLFYP23TAfapmqaPWt95nLNb5UDq+Mtcq8+L4oxLx3KzuqPD5yz0p477QNGM9AtuWKL2An+zIV4WCS38+/kV0tsIWmtVlfbvUlNrv58h+LbZ6IaKpEXvSkeUOjYrC32PmSbg5KkxGWv8S8+2AzSxREYOzpAA=
  app: lpa2-2019
  on:
    repo: MohamedCA2018/LPA2
