language: ruby
rvm:
- 2.3.3
deploy:
  provider: heroku
  api_key:
    secure: iCLmkoT2dZMRNkYHlzTTbUOS6Yla/64dkMm9ynpAr8iIMxCfprvh1WVjTvQTqeFDwJW+VDvhJqbPUXEGeB9UEnBurOrOsgy01/akEj2JnOoF6gn34Mt8E1pOLAO8i3TGbihUpPn7+KucWDcHyBdt5owHVML5QAfwB5SWld1nlDLks+u7qU5fBFufdzhAabXy86ygxGUpsvFNSkmPguYRBchuunKaifpt0t9EbG6QojrVOhaWZc/Sb1OruQcyHyaxNuSIZtwISN1Gmsezrwsxr5YUFbnApxlrKBU8jdiEJujRfsjEAulY8zPmogYuGJIeDbIEyw+y1knqN+CEwU96YZTLV5URF1phJUeN5X39iefpecZAM5QY5WQs+Zil0SL+fY2wxjFbbK56KnhUrY5gMaAoCViJCWvsNTPydvTCKf8PJkU3PUfpbOicZ146nhV7aZrRQ+NVOwnR2m/+cmVwH71mCjbeoLnHEnxydDqObL4AUJbdJxAIdD/lfLBTy/5Iq5jSPIOC0HjTJ8HTDEFUDl/dKy2kAQzdgqYlErbllJXZxDoRENDRUVqpYJ0Di1qxQ0jtOq2s2iTJXMF+CVTt+ZTXPODC9wY/XfztS1JCQUyMuSnWmng+1N69OgBJgqz3piqURYFxXuXZvhtXl/MAbVd2poDy4HunHc7OSjrEHmk=
  app: lpa2-2019
  on:
    repo: MohamedCA2018/LPA2
