language: ruby
rvm:
- 2.3.3
deploy:
  provider: heroku
  api_key:
    secure: C/a3xhnsHI+SXvNdk3aetQol46oPyDFCcdaAwyQ/e7e/uTuiQegYaBXY/wj/Jd4dXHBb9NvYZ4ifeVzMoqdcRoTXmpi10LFj2K/NUx87hfQRcfGD8cWXMAke37IL75dR7rBRiucPZV74B55Cqxgfxh011iSLWKLAvkdHFy9WHUDo5viUwm6WTaWz2MZ6BLA5LS9IEDC9hOiVzj+MM8AMQ4djPjYG3MpXO3tkNZaMIDDu8b3Edkoi/fbTlj9Gug8xmHPnloSj27qatp/tKlDASuDlDW5s2C/6K7Dqu+UiQ8itr6deE1vxN5j7NybM6aIDumK7hqyuOpkpmwDs3o2L+Bv2MzORsTzl3dr3E6Bnx6vKz990URgDJS2JPJ20VUkMzZ3+yPf2dmbQxZa2Mj+mOsbRXHulEKxpbg3et7M5KN95CIWpMAfBZLWHbapSfSts4PC3F0S3Od1Jg3ZrZHH+wYK1Yi60Q/dHZ2OX9WfO5mFFHMMs5g3OEL0w4/hOSoz/FOXc9GLPX88/s1i5OArhHRNcaJ5sqXYXlDTpsyB4xpvRdONC0xv45OpPsgCtTrt96nCV1/xPGKmGSOx9i1K/hlO9+d+5jT0ibFT22uQ544vDKAMZyr9R3GhHCR8Ycd7wNjBaZAFS4LekIebQYQgSdkVDepxvGfXdUN23X4WvyEc=
  app: lpa2-2019
  on:
    repo: MohamedCA2018/LPA2
